# Generated by Django 6.1 on 2026-09-12 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='photouser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile/'),
        ),
        migrations.AlterField(
            model_name='photouser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
