# Generated by Django 6.1 on 2026-08-29 19:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('ANY', 'Anna Nery'), ('ATL', 'Atlanta'), ('MQU', 'Maria Quitéria')], max_length=3)),
                ('date_report', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_incident', models.CharField(choices=[('FAC', 'First Aid Case'), ('MTC', 'Medical Treatment Case'), ('RWC', 'Restricted Work Case'), ('LTI', 'Lost Time Injury')], max_length=3)),
                ('status', models.CharField(choices=[('OPE', 'Open'), ('CLO', 'Closed')], default='OPE', max_length=3)),
                ('cod_sys', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_incident', models.DateTimeField()),
                ('underlying_causes', models.TextField(blank=True)),
                ('location_incident', models.CharField(choices=[('ACC', 'Accommodation'), ('AST', 'Ashore / Travel'), ('CAT', 'Cargo Tank'), ('ENR', 'Engine Room'), ('HEL', 'Helideck'), ('MEP', 'Main deck except process'), ('MOZ', 'MOB / Zodiac'), ('PCA', 'Process incl. HP compressor area'), ('PUP', 'Pump Room'), ('SIY', 'Site / Yard'), ('OTH', 'Other')], max_length=3)),
                ('work_days_lost', models.PositiveIntegerField(default=0)),
                ('bodypart_injured', models.CharField(choices=[('ARM', 'Arm(s)'), ('BAC', 'Back'), ('EYE', 'Eye(s)'), ('FIN', 'Finger(s)'), ('FOO', 'Foot / Feet'), ('HAN', 'Hand'), ('HEA', 'Head'), ('INT', 'Internal Injury'), ('LEG', 'Leg(s)'), ('LOW', 'Lower body'), ('OTH', 'Other'), ('SHO', 'Shoulder'), ('TOR', 'Torso')], max_length=3)),
                ('employer', models.CharField(max_length=50)),
                ('injured_person_name', models.CharField(blank=True, max_length=80)),
                ('condition_injured', models.TextField(blank=True)),
                ('risk_potencial', models.CharField(choices=[('ONE', '1 <|> 1 -> 1'), ('TWO', '1 <|> 2 -> 2'), ('THR', '2 <|> 1 -> 2'), ('FOU', '1 <|> 3 -> 3'), ('FIV', '3 <|> 1 -> 3'), ('SIX', '1 <|> 4 -> 4'), ('SEV', '2 <|> 2 -> 4'), ('EIG', '4 <|> 1 -> 4'), ('NIN', '1 <|> 5 -> 5'), ('TEN', '5 <|> 1 -> 5'), ('ELE', '2 <|> 3 -> 6'), ('TWE', '3 <|> 2 -> 6'), ('THI', '2 <|> 4 -> 8'), ('FOT', '4 <|> 2 -> 8'), ('FIF', '3 <|> 3 -> 9'), ('SIE', '2 <|> 5 -> 10'), ('SET', '5 <|> 2 -> 10'), ('EIT', '3 <|> 4 -> 12'), ('NIT', '4 <|> 3 -> 12'), ('TWN', '3 <|> 5 -> 15'), ('TON', '5 <|> 3 -> 15'), ('TTW', '4 <|> 4 -> 16'), ('TTH', '4 <|> 5 -> 20'), ('TFO', '5 <|> 4 -> 20'), ('TFI', '5 <|> 5 -> 25')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_injuries', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_injuries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Injury',
                'verbose_name_plural': 'Injuries',
                'ordering': ['-date_incident'],
            },
        ),
        migrations.CreateModel(
            name='ActionInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_date_action', models.DateTimeField()),
                ('completed_date_action', models.DateTimeField(blank=True, null=True)),
                ('task', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('COM', 'Completed'), ('EXP', 'Expired')], default='ACT', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injury_actions', to=settings.AUTH_USER_MODEL)),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incident.injury')),
            ],
            options={
                'verbose_name': 'Injury Action',
                'verbose_name_plural': 'Injury Actions',
                'ordering': ['limit_date_action'],
            },
        ),
        migrations.CreateModel(
            name='TypeAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ASS', 'Assault or Violent Act'), ('AVI', 'Aviation accidents'), ('CAU', 'Caught In, Under or Between (excl. dropped objects)'), ('CON', 'Confined Space'), ('CUT', 'Cut, Puncture, Scrape'), ('DRO', 'Dropped Objects'), ('EXB', 'Explosions or Burns'), ('EXE', 'Exposure: Electrical'), ('EXP', 'Exposure: Noise, Chemical, Biological, Vibration'), ('FAL', 'Falls from height'), ('ILL', 'Illness'), ('OTH', 'Other'), ('OVE', 'Overexertion / Strain'), ('PRE', 'Pressure release'), ('SLI', 'Slips and Trips (at the same height)'), ('STR', 'Struck By (excl. dropped object)'), ('WAT', 'Water related, drowning')], max_length=3)),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accident_types', to='incident.injury')),
            ],
            options={
                'verbose_name': 'Type of Accident',
                'verbose_name_plural': 'Types of Accident',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ABR', 'Abrasion'), ('ALL', 'Allergic Reaction'), ('AMP', 'Amputation'), ('BRU', 'Bruise'), ('BUR', 'Burn Chemical'), ('BUE', 'Burn Electrical'), ('BUT', 'Burn Thermal'), ('CON', 'Concussion'), ('COT', 'Contusion'), ('CRU', 'Crush'), ('DIS', 'Dislocation'), ('DYS', 'Dysbaric illness'), ('ELE', 'Electrocution'), ('FOR', 'Foreign Body'), ('FRA', 'Fracture'), ('GAS', 'Gassing'), ('HEA', 'Hearing Loss'), ('INC', 'Incision'), ('INF', 'Infection'), ('ING', 'Ingestion'), ('INS', 'Insect / Animal Bite or Sting'), ('IRR', 'Irritation'), ('LAC', 'Laceration'), ('LOC', 'Loss of Consciousness'), ('LOS', 'Loss of Sight'), ('MEN', 'Mental illness'), ('OTH', 'Other'), ('PEN', 'Penetration'), ('PUN', 'Puncture'), ('RAD', 'Radiation'), ('RES', 'Respiratory'), ('SCA', 'Scald'), ('SKI', 'Skin Disease'), ('SPR', 'Sprain'), ('STA', 'Stain'), ('TRO', 'Tropical Disease')], max_length=3)),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_types', to='incident.injury')),
            ],
            options={
                'verbose_name': 'Type of Injury',
                'verbose_name_plural': 'Types of Injury',
                'ordering': ['name'],
            },
        ),
    ]
