# Generated by Django 6.1 on 2026-09-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='unit',
            field=models.CharField(choices=[('ANY', 'Anna Nery'), ('ATL', 'Atlanta'), ('MQU', 'Maria Quitéria'), ('OOW', 'Office or Warehouses')], max_length=3),
        ),
    ]
